repos:
  - repo: local
    hooks:
      - id: check-yaml
        name: Check YAML
        entry: uv run --locked check-yaml
        language: system
        types: [yaml]
      - id: check-json
        name: Check JSON
        entry: uv run --locked check-json
        language: system
        types: [json]
      - id: check-toml
        name: Check TOML
        entry: uv run --locked check-toml
        language: system
        types: [toml]
      - id: end-of-file-fixer
        name: Fix end of files
        entry: uv run --locked end-of-file-fixer
        language: system
        types: [text]
      - id: trailing-whitespace
        name: Trim trailing whitespace
        entry: uv run --locked trailing-whitespace-fixer
        language: system
        types: [text]
      - id: check-added-large-files
        name: Check added large files
        entry: uv run --locked check-added-large-files --maxkb=1000
        language: system
      - id: ruff
        name: Ruff
        entry: uv run --locked ruff check --fix
        language: system
        types: [python]
      - id: black
        name: Black
        entry: uv run --locked black
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: uv run --locked mypy psysafe examples
        language: system
        pass_filenames: false
