# Custom Cleanup Configuration for Testing
cleanup_phases:
  - dead_code_removal
  - documentation_refresh
  - code_consolidation

safety:
  backup_enabled: true
  backup_directory: "./custom_backups"
  validation_enabled: true
  rollback_on_failure: true

dead_code_removal:
  remove_unused_imports: true
  remove_unused_functions: true
  remove_unused_variables: false  # More conservative
  exclude_patterns:
    - "test_*"
    - "*_test.py"

documentation_refresh:
  add_missing_docstrings: true
  update_outdated_comments: true
  generate_module_docs: false  # Skip for this test

code_consolidation:
  merge_similar_functions: true
  consolidate_imports: true
  remove_duplicate_code: true

reporting:
  generate_html_report: true
  generate_json_report: true
  verbose_output: true