name: Feature Request
description: Suggest an idea for PsySafe-AI
title: "[FEAT] "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        We love hearing new ideas! Please define the scope and reasoning behind the feature request below.
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe it.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution or feature you'd like to see added.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
    validations:
      required: false
